openapi: 3.0.3
info:
  title: SistemaVendas
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/login:
    post:
      summary: ''
      operationId: postApiLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/validateToken:
    get:
      summary: ''
      operationId: getApiValidateToken
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: 'Token de autorização não encontrado'
                properties:
                  error:
                    type: string
                    example: 'Token de autorização não encontrado'
      tags:
        - Endpoints
      security: []
  /api/recoverPassword:
    post:
      summary: ''
      operationId: postApiRecoverPassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/updatePassword:
    post:
      summary: ''
      operationId: postApiUpdatePassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/logout:
    post:
      summary: ''
      operationId: postApiLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/user/all:
    get:
      summary: ''
      operationId: getApiUserAll
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Token not provided'
                properties:
                  message:
                    type: string
                    example: 'Token not provided'
      tags:
        - Endpoints
      security: []
  /api/user/search:
    get:
      summary: ''
      operationId: getApiUserSearch
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Token not provided'
                properties:
                  message:
                    type: string
                    example: 'Token not provided'
      tags:
        - Endpoints
      security: []
  /api/user/cards:
    get:
      summary: ''
      operationId: getApiUserCards
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Token not provided'
                properties:
                  message:
                    type: string
                    example: 'Token not provided'
      tags:
        - Endpoints
      security: []
  /api/user/me:
    get:
      summary: ''
      operationId: getApiUserMe
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Token not provided'
                properties:
                  message:
                    type: string
                    example: 'Token not provided'
      tags:
        - Endpoints
      security: []
  /api/user/create:
    post:
      summary: ''
      operationId: postApiUserCreate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/user/{id}':
    patch:
      summary: ''
      operationId: patchApiUserId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the user.'
        example: aut
        required: true
        schema:
          type: string
  '/api/user/block/{id}':
    post:
      summary: ''
      operationId: postApiUserBlockId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the block.'
        example: quas
        required: true
        schema:
          type: string
  /api/facility/search:
    get:
      summary: ''
      operationId: getApiFacilitySearch
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Token not provided'
                properties:
                  message:
                    type: string
                    example: 'Token not provided'
      tags:
        - Endpoints
      security: []
  '/api/facility/{id}':
    get:
      summary: ''
      operationId: getApiFacilityId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Token not provided'
                properties:
                  message:
                    type: string
                    example: 'Token not provided'
      tags:
        - Endpoints
      security: []
    patch:
      summary: ''
      operationId: patchApiFacilityId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiFacilityId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the facility.'
        example: adipisci
        required: true
        schema:
          type: string
  /api/facility/create:
    post:
      summary: ''
      operationId: postApiFacilityCreate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/component/search:
    get:
      summary: ''
      operationId: getApiComponentSearch
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Token not provided'
                properties:
                  message:
                    type: string
                    example: 'Token not provided'
      tags:
        - Endpoints
      security: []
  '/api/component/{id}':
    get:
      summary: ''
      operationId: getApiComponentId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Token not provided'
                properties:
                  message:
                    type: string
                    example: 'Token not provided'
      tags:
        - Endpoints
      security: []
    patch:
      summary: ''
      operationId: patchApiComponentId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiComponentId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the component.'
        example: dolores
        required: true
        schema:
          type: string
  /api/component/create:
    post:
      summary: ''
      operationId: postApiComponentCreate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/action/search:
    get:
      summary: ''
      operationId: getApiActionSearch
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Token not provided'
                properties:
                  message:
                    type: string
                    example: 'Token not provided'
      tags:
        - Endpoints
      security: []
  '/api/action/{id}':
    get:
      summary: ''
      operationId: getApiActionId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Token not provided'
                properties:
                  message:
                    type: string
                    example: 'Token not provided'
      tags:
        - Endpoints
      security: []
    patch:
      summary: ''
      operationId: patchApiActionId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiActionId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the action.'
        example: sint
        required: true
        schema:
          type: string
  /api/action/create:
    post:
      summary: ''
      operationId: postApiActionCreate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
