openapi: 3.0.3
info:
  title: SistemaVendas
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/login:
    post:
      summary: ''
      operationId: postApiLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/validateToken:
    get:
      summary: ''
      operationId: getApiValidateToken
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: 'Token de autorização não encontrado'
                properties:
                  error:
                    type: string
                    example: 'Token de autorização não encontrado'
      tags:
        - Endpoints
      security: []
  /api/recoverPassword:
    post:
      summary: ''
      operationId: postApiRecoverPassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/updatePassword:
    post:
      summary: ''
      operationId: postApiUpdatePassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/logout:
    post:
      summary: ''
      operationId: postApiLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/user/all:
    get:
      summary: ''
      operationId: getApiUserAll
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Token not provided'
                properties:
                  message:
                    type: string
                    example: 'Token not provided'
      tags:
        - Endpoints
      security: []
  /api/user/search:
    get:
      summary: ''
      operationId: getApiUserSearch
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Token not provided'
                properties:
                  message:
                    type: string
                    example: 'Token not provided'
      tags:
        - Endpoints
      security: []
  /api/user/cards:
    get:
      summary: ''
      operationId: getApiUserCards
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Token not provided'
                properties:
                  message:
                    type: string
                    example: 'Token not provided'
      tags:
        - Endpoints
      security: []
  /api/user/me:
    get:
      summary: ''
      operationId: getApiUserMe
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Token not provided'
                properties:
                  message:
                    type: string
                    example: 'Token not provided'
      tags:
        - Endpoints
      security: []
  /api/user/create:
    post:
      summary: ''
      operationId: postApiUserCreate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/user/{id}':
    patch:
      summary: ''
      operationId: patchApiUserId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the user.'
        example: vitae
        required: true
        schema:
          type: string
  '/api/user/block/{id}':
    post:
      summary: ''
      operationId: postApiUserBlockId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the block.'
        example: quidem
        required: true
        schema:
          type: string
  /api/client/search:
    get:
      summary: ''
      operationId: getApiClientSearch
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Token not provided'
                properties:
                  message:
                    type: string
                    example: 'Token not provided'
      tags:
        - Endpoints
      security: []
  /api/client/create:
    post:
      summary: ''
      operationId: postApiClientCreate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/client/{id}':
    patch:
      summary: ''
      operationId: patchApiClientId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiClientId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the client.'
        example: veritatis
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
